mybatis-plus:
  mapper-locations: classpath:com/xiao/xoj/mapper/*.xml
  type-aliases-package: com.xiao.xoj.pojo.entity
  configuration:
    cache-enabled: true
  # 关闭打印 mybatis-plus 的 LOGO
  global-config:
    banner: false

# 消费者将要去访问的微服务名称（注册成功进入nacos的微服务提供者）
#service-url:
#  name: xoj-judge-service # 服务名

spring:
  profiles:
    active: prod
  application:
    name: xoj-judge-service
